// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTyOVvrBP1WqE-7_2EoYFcnZyZl0tJZqA',
    appId: '1:374082478451:web:ea434eb7c0bf3a13b96506',
    messagingSenderId: '374082478451',
    projectId: 'contact-e507a',
    authDomain: 'contact-e507a.firebaseapp.com',
    storageBucket: 'contact-e507a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj5woharHckxF3nloryD4rXC6DuWcvMUQ',
    appId: '1:374082478451:android:251715d48da37d11b96506',
    messagingSenderId: '374082478451',
    projectId: 'contact-e507a',
    storageBucket: 'contact-e507a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-OY66iRl-IPganG_ZChVCOXF44nP44w',
    appId: '1:374082478451:ios:3f88418cc533cc05b96506',
    messagingSenderId: '374082478451',
    projectId: 'contact-e507a',
    storageBucket: 'contact-e507a.appspot.com',
    iosClientId: '374082478451-tlj816pfggl46vc2gqbttb12elr2m63p.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-OY66iRl-IPganG_ZChVCOXF44nP44w',
    appId: '1:374082478451:ios:3f88418cc533cc05b96506',
    messagingSenderId: '374082478451',
    projectId: 'contact-e507a',
    storageBucket: 'contact-e507a.appspot.com',
    iosClientId: '374082478451-tlj816pfggl46vc2gqbttb12elr2m63p.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactapp',
  );
}
